variable "az_resource_group" {
  description = "Target resource group"
  type        = object({
    name     = string
    location = string
  })
  validation {
    condition = length(var.az_resource_group.name) < 90
    error_message = "AZ resource group names must use fewer than 90 characters"
  }
}

variable "az_name_prefix" {
  description = "Prefix for resource names to ensure unique naming"
  type        = string
}

variable "az_region" {
  description = "Target AZ region (e.g. eastus1)"
  type        = string
}

variable "app_service_plan" {
    description = "https://learn.microsoft.com/en-us/azure/app-service/overview-hosting-plans"
    type        = string
}

variable "virtual_network_subnet_id" {
    description = "The subnet id which will be used by this Web App for regional virtual network integration: https://docs.microsoft.com/en-us/azure/app-service/overview-vnet-integration#regional-virtual-network-integration"
    type        = string
}

variable "connection_string" {
    description = "Connection string of db used by App Service"
    type        = string
}

variable "database_type" {
    description = "Type of database used by the App Service (e.g. SQLServer)"
    type        = string
}

variable "bu" {
    description = "Customer business unit (e.g. flg)"
    type        = string
}

variable "environment" {
    description = "Deployment tier (e.g. dev)"
    type        = string
}

variable "owner" {
    description = "Email address of the party who owns this "
    type        = string
}

variable "service_app_client_id" {
    description = "Azure AD App Registration Client Id"
    type        = string
}

variable "service_app_client_secret" {
    description = "Azure AD App Registration Client Id"
    type        = string
}

variable "service_identifier_uri" {
    description = "Used as an audience in the authN token generated by Azure AD"
    type        = string
}

variable "az_ad_tenant_id" {
    description = "ID of our Azure AD Tenant"
    type        = string
}
